ALTER TABLE inventory_item 
ADD COLUMN IF NOT EXISTS lead_time INTEGER DEFAULT 3,
ADD COLUMN IF NOT EXISTS alert_level DOUBLE PRECISION DEFAULT 10.0,
ADD COLUMN IF NOT EXISTS reorder_count DOUBLE PRECISION DEFAULT 50.0;
