-- V20 Add Missing Entity Fields for Restaurant and Supplier

-- Add missing fields to restaurant
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS onboarding_status VARCHAR(50) DEFAULT 'PENDING';
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS contact_person VARCHAR(255);
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS alternate_phone VARCHAR(50);
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS kyc_vetted BOOLEAN DEFAULT FALSE;
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS vetting_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS performance_metrics JSONB;

-- Add missing fields to supplier
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS organization_id VARCHAR(50);
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS regions TEXT;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS contact_person VARCHAR(255);
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS alternate_phone VARCHAR(50);
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS kyc_vetted BOOLEAN DEFAULT FALSE;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS vetting_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS performance_metrics JSONB;
