server:
  port: 8081

spring:
  application:
    name: shopro-marketplace-be
  
  datasource:
    url: jdbc:postgresql://localhost:5432/shopro_marketplace_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    mls.shopro.mplace: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
