-- V6__restaurant_the_market_table.sql
-- Restaurant: The Market Table — New York, NY
-- Cuisine: Modern Casual (American fusion, brunch, small plates)
-- Price Tier: MID | Target Food Cost: 30% | Tax: 10%
-- Country: United States | Timezone: America/New_York
-- Generated by: restaurant-scenario-builder skill (DEFAULT mode)
-- ══════════════════════════════════════════════════════════════════════════

-- All values are hardcoded for idempotency (same script = same data every time).
-- Restaurant ID = 3 (avoids conflicting with IDs 1 & 2 used by other seeders).

-- ── RESTAURANT ────────────────────────────────────────────────────────────
INSERT INTO restaurant (id, name, timezone, created_at, updated_at)
VALUES (3, 'The Market Table', 'America/New_York', '2026-01-01', '2026-01-01')
ON CONFLICT DO NOTHING;

-- ── DINING TABLES (24 tables: 4 × 6 grid layout) ───────────────────────
-- Front row: T01-T06 (intimate, 2-top), Middle: T07-T18 (standard, 4-top),
-- Back row: T19-T24 (large party, 6-top)
INSERT INTO dining_table (restaurant_id, table_number, capacity, status, pos_x, pos_y)
VALUES
  (3,'T01',2,'AVAILABLE', 40,  40),(3,'T02',2,'AVAILABLE',120,  40),(3,'T03',2,'AVAILABLE',200,  40),(3,'T04',2,'AVAILABLE',280,  40),(3,'T05',2,'AVAILABLE',360,  40),(3,'T06',2,'AVAILABLE',440,  40),
  (3,'T07',4,'AVAILABLE', 40, 120),(3,'T08',4,'AVAILABLE',120, 120),(3,'T09',4,'AVAILABLE',200, 120),(3,'T10',4,'AVAILABLE',280, 120),(3,'T11',4,'AVAILABLE',360, 120),(3,'T12',4,'AVAILABLE',440, 120),
  (3,'T13',4,'AVAILABLE', 40, 200),(3,'T14',4,'AVAILABLE',120, 200),(3,'T15',4,'AVAILABLE',200, 200),(3,'T16',4,'AVAILABLE',280, 200),(3,'T17',4,'AVAILABLE',360, 200),(3,'T18',4,'AVAILABLE',440, 200),
  (3,'T19',6,'AVAILABLE', 40, 280),(3,'T20',6,'AVAILABLE',160, 280),(3,'T21',6,'AVAILABLE',280, 280),(3,'T22',6,'AVAILABLE',400, 280),(3,'T23',6,'AVAILABLE', 80, 280),(3,'T24',6,'AVAILABLE',480, 280)
ON CONFLICT (restaurant_id, table_number) DO NOTHING;

-- ── SUPPLIERS ─────────────────────────────────────────────────────────────
-- payment_mode, payment_terms, lead_time_days, minimum_order_value: added by V7 migration
-- preferred_supplier_id: set in V7 migration (ingredient.preferred_supplier_id)
INSERT INTO supplier (id, restaurant_id, name, contact_name, phone, email,
   account_number, is_active, created_at, updated_at)
VALUES
  -- Hudson Valley Purveyors (PRODUCE)
  (101, 3, 'Hudson Valley Purveyors',  'Sarah Mitchell',    '+1-212-555-0101', 'orders@hvpurveyors.com',
   'HVP-2026-001', true, '2026-01-01', '2026-01-01'),
  -- Prime Meats NYC (MEAT & POULTRY)
  (102, 3, 'Prime Meats NYC',          'Robert O''Brien',   '+1-212-555-0102', 'rfq@primemeatsnyc.com',
   'PMN-2026-001', true, '2026-01-01', '2026-01-01'),
  -- Fresh Catch Seafood (SEAFOOD)
  (103, 3, 'Fresh Catch Seafood',      'Linda Chen',        '+1-212-555-0103', 'supply@freshcatchseafood.com',
   'FCS-2026-001', true, '2026-01-01', '2026-01-01'),
  -- Gotham Dairy Supply (DAIRY)
  (104, 3, 'Gotham Dairy Supply',     'Mike Patterson',   '+1-212-555-0104', 'orders@gothamdairy.com',
   'GDS-2026-001', true, '2026-01-01', '2026-01-01'),
  -- Empire Dry Goods (DRY GOODS & GROCERY)
  (105, 3, 'Empire Dry Goods',        'Tony Russo',        '+1-212-555-0105', 'sales@empiredrygoods.com',
   'EDG-2026-001', true, '2026-01-01', '2026-01-01')
ON CONFLICT (restaurant_id, name) DO NOTHING;

-- ── INGREDIENTS ────────────────────────────────────────────────────────────
-- Column order: id, restaurant_id, item_code, description, inventory_type, category,
--   purchase_unit, case_pack_size, purchase_unit_price,
--   recipe_unit, ru_per_pu, yield_pct, inventory_unit, iu_per_pu,
--   oz_weight_per_cup, packed_by, par_level, on_hand,
--   preferred_supplier_id: set in V7 migration (ingredient.preferred_supplier_id)
--   shelf_life_days: set in V8 migration (ingredient.shelf_life_days)
-- par_level  = target stock to maintain (1 week supply at current usage rate)
-- on_hand    = current physical count (restaurant just opened, at par)
-- packed_by  = WEIGHT | VOLUME (only for bulk dry goods measured by volume)
-- oz_weight_per_cup = density for volume↔weight conversion (null for countables)
--
-- INV UNIT PER PU (iu_per_pu):
--   LB   ingredients → 1 LB per PU (case = N lbs)
--   EACH ingredients → 1 EACH per PU
--   GALLON ingredients → 1 GALLON per PU
--   LITER ingredients → 1 LITER per PU
--   JAR ingredients → 1 JAR per PU
--   BUNCH ingredients → 1 BUNCH per PU
--
-- YIELD % EXPLANATION (yield_pct = usable portion after trim/prep):
--   yield_pct = (usable pounds plated) / (as-purchased pounds received)
--   Example: whole beef tenderloin received at 24.99/lb weighs 10 lbs,
--   after trimming fat/covers/chain: 7.8 lbs plated → yield = 78% = 0.7800
--   ru_cost = purchase_price / ru_per_pu / yield_pct = cost of usable portion
INSERT INTO ingredient
  (id, restaurant_id, item_code, description, inventory_type, category,
   purchase_unit, case_pack_size, purchase_unit_price,
   recipe_unit, ru_per_pu, yield_pct, inventory_unit, iu_per_pu,
   oz_weight_per_cup, packed_by, par_level, on_hand,
   is_active, created_at, updated_at)
VALUES
  -- PRODUCE (sup1: Hudson Valley Purveyors — preferred supplier 101)
  (301, 3, 'ING01', 'Avocados (Hass)',             'FOOD', 'PRODUCE',           'EACH',  '48 ct',    1.79,  'EACH',   1.0000, 1.0000, 'EACH',  1.0000, 4.0000, 'WEIGHT', 20.0, 20.0, true, '2026-01-01','2026-01-01'),
  -- Roma Tomatoes: shelf_life 5 days (core, refrigerate after cutting)
  (302, 3, 'ING02', 'Roma Tomatoes',               'FOOD', 'PRODUCE',           'LB',    '20 lb',   2.49,  'LB',     1.0000, 0.9200, 'LB',    1.0000,    0.0, null,     40.0, 40.0, true, '2026-01-01','2026-01-01'),
  -- Yellow Onions: shelf_life 7 days (dry, store in cool dark area)
  (303, 3, 'ING03', 'Yellow Onions',              'FOOD', 'PRODUCE',           'LB',    '50 lb',   1.29,  'LB',     1.0000, 0.9500, 'LB',    1.0000,    0.0, null,     60.0, 60.0, true, '2026-01-01','2026-01-01'),
  -- Fresh Arugula: shelf_life 3 days (very perishable, keep cold)
  (304, 3, 'ING04', 'Fresh Arugula',              'FOOD', 'PRODUCE',           'LB',    '1 lb',    4.99,  'LB',     1.0000, 0.9000, 'LB',    1.0000,    0.0, null,     15.0, 15.0, true, '2026-01-01','2026-01-01'),
  -- Free-Range Eggs: shelf_life 10 days (from pack date, refrigerate)
  (305, 3, 'ING05', 'Free-Range Eggs',            'FOOD', 'PRODUCE',           'EACH',  '15 dz',   5.99,  'EACH',   1.0000, 1.0000, 'EACH',  1.0000,    0.0, null,     60.0, 60.0, true, '2026-01-01','2026-01-01'),
  -- Fresh Herbs: shelf_life 3 days (fragile, cold storage essential)
  (306, 3, 'ING06', 'Fresh Herbs (Mixed Bundle)', 'FOOD', 'PRODUCE',           'BUNCH', '12 bch',  2.99,  'LB',     0.7500, 0.7500, 'LB',    0.2500,    0.0, null,     10.0, 10.0, true, '2026-01-01','2026-01-01'),
  -- MEAT & SEAFOOD (sup2: Prime Meats NYC — preferred supplier 102)
  -- Beef Tenderloin: shelf_life 5 days (refrigerate, whole muscle keeps longer)
  (307, 3, 'ING07', 'Beef Tenderloin (Whole)',    'FOOD', 'MEAT',              'LB',    null,     24.99,  'LB',     1.0000, 0.7800, 'LB',    1.0000,    0.0, null,     50.0, 50.0, true, '2026-01-01','2026-01-01'),
  -- Lamb Rack: shelf_life 4 days (smaller cut, higher surface area)
  (308, 3, 'ING08', 'Lamb Rack (Frenched 7-Bone)','FOOD','MEAT',              'LB',    null,     18.99,  'LB',     1.0000, 0.8000, 'LB',    1.0000,    0.0, null,     30.0, 30.0, true, '2026-01-01','2026-01-01'),
  -- Heritage Pork Belly: shelf_life 6 days (fat cap slows oxidation)
  (311, 3, 'ING11', 'Heritage Pork Belly',         'FOOD','MEAT',              'LB',    null,      6.99,  'LB',     1.0000, 0.9000, 'LB',    1.0000,    0.0, null,     40.0, 40.0, true, '2026-01-01','2026-01-01'),
  -- Free-Range Duck Breast: shelf_life 4 days (skin-on, refrigerate)
  (312, 3, 'ING12', 'Free-Range Duck Breast',      'FOOD','POULTRY',           'LB',    null,      9.99,  'LB',     1.0000, 0.8200, 'LB',    1.0000,    0.0, null,     30.0, 30.0, true, '2026-01-01','2026-01-01'),
  -- SEAFOOD (sup3: Fresh Catch Seafood — preferred supplier 103)
  -- Atlantic Salmon: shelf_life 2 days (most perishable, use within 48 hrs)
  (309, 3, 'ING09', 'Atlantic Salmon (Fresh Fillet)','FOOD','SEAFOOD',         'LB',    null,     12.99,  'LB',     1.0000, 0.8500, 'LB',    1.0000,    0.0, null,     40.0, 40.0, true, '2026-01-01','2026-01-01'),
  -- Yellowfin Tuna: shelf_life 2 days (sushi-grade, very high risk)
  (310, 3, 'ING10', 'Yellowfin Tuna (Sushi Grade)','FOOD','SEAFOOD',          'LB',    null,     22.99,  'LB',     1.0000, 0.9000, 'LB',    1.0000,    0.0, null,     20.0, 20.0, true, '2026-01-01','2026-01-01'),
  -- DAIRY (sup4: Gotham Dairy Supply — preferred supplier 104)
  -- Butter: shelf_life 14 days (sealed, refrigerate)
  (313, 3, 'ING13', 'Unsalted Butter',            'FOOD','DAIRY',             'LB',    '36 lb',   5.50,  'LB',     1.0000, 1.0000, 'LB',    1.0000,    0.0, null,     30.0, 30.0, true, '2026-01-01','2026-01-01'),
  -- Heavy Cream: shelf_life 7 days (pasteurized ultra-fresh, refrigerate)
  (314, 3, 'ING14', 'Heavy Cream',                 'FOOD','DAIRY',             'GALLON','1 gal',   8.99,  'GALLON', 1.0000, 1.0000, 'GALLON', 1.0000, 8.0000, 'VOLUME', 10.0, 10.0, true, '2026-01-01','2026-01-01'),
  -- Burrata: shelf_life 5 days (fresh, brine-packed, highly perishable)
  (315, 3, 'ING15', 'Burrata Cheese (Fresh)',      'FOOD','DAIRY',             'EACH',  '4 pc',    6.99,  'EACH',   1.0000, 1.0000, 'EACH',  1.0000,    0.0, null,     24.0, 24.0, true, '2026-01-01','2026-01-01'),
  -- DRY GOODS (sup5: Empire Dry Goods — preferred supplier 105)
  -- Flour: shelf_life NULL (shelf-stable, no expiry concern for culinary use)
  (316, 3, 'ING16', 'All-Purpose Flour (Unbleached)','FOOD', 'DRY_GOODS',         'LB',    '50 lb',   0.56,  'LB',     1.0000, 1.0000, 'LB',    1.0000, 4.5000, 'WEIGHT', 200.0, 200.0, true, '2026-01-01','2026-01-01'),
  -- Cane Sugar: shelf_life NULL (shelf-stable, indefinite if stored dry)
  (317, 3, 'ING17', 'Cane Sugar (Fine)',           'FOOD',    'DRY_GOODS',         'LB',    '50 lb',   0.79,  'LB',     1.0000, 1.0000, 'LB',    1.0000, 7.0000, 'WEIGHT', 100.0, 100.0, true, '2026-01-01','2026-01-01'),
  -- Extra Virgin Olive Oil: shelf_life NULL (shelf-stable if sealed, 18-month best-by but safe)
  (318, 3, 'ING18', 'Extra Virgin Olive Oil',      'FOOD',    'GROCERY_DRY_GOODS', 'LITER', '6 bt',   12.99,  'LITER',  1.0000, 1.0000, 'LITER',  1.0000, 7.7000, 'VOLUME', 12.0, 12.0, true, '2026-01-01','2026-01-01'),
  -- Tahini: shelf_life NULL (sealed jar, 12-month best-by but no microbiological expiry in use)
  (319, 3, 'ING19', 'Tahini (Premium, Stone-Ground)','FOOD',  'GROCERY_DRY_GOODS', 'JAR',   '16 oz',   8.49,  'JAR',    1.0000, 1.0000, 'JAR',    1.0000,    0.0, null,     20.0, 20.0, true, '2026-01-01','2026-01-01'),
  -- Maple Syrup: shelf_life NULL (shelf-stable if refrigerated after opening)
  (320, 3, 'ING20', 'Maple Syrup (Grade A Dark)',  'FOOD',    'GROCERY_DRY_GOODS', 'GALLON','4 gal',  24.99,  'GALLON', 1.0000, 1.0000, 'GALLON', 1.0000, 11.5000, 'VOLUME', 4.0, 4.0, true, '2026-01-01','2026-01-01')
ON CONFLICT (restaurant_id, item_code) DO NOTHING;

-- ── MENU COST GROUPS ─────────────────────────────────────────────────────
-- revenueCategory values: FOOD | SOFT_BEV | LIQUOR | BEER | WINE | MERCH
INSERT INTO menu_cost_group
  (id, restaurant_id, name, revenue_category, display_order, created_at)
VALUES
  (301, 3, 'Breakfast & Brunch',   'FOOD',     1, '2026-01-01'),
  (302, 3, 'Small Plates',        'FOOD',     2, '2026-01-01'),
  (303, 3, 'Mains',               'FOOD',     3, '2026-01-01'),
  (304, 3, 'Soups & Salads',       'FOOD',     4, '2026-01-01'),
  (305, 3, 'Desserts',             'FOOD',     5, '2026-01-01'),
  (306, 3, 'Coffee & Tea',          'SOFT_BEV', 6, '2026-01-01'),
  (307, 3, 'Wine by the Glass',    'WINE',     7, '2026-01-01'),
  (308, 3, 'Craft Beer',            'BEER',     8, '2026-01-01')
ON CONFLICT DO NOTHING;

-- ── MENU ITEMS ────────────────────────────────────────────────────────────
-- pos_id format: <group_prefix><nn>
-- sell_price: calculated as (plate_cost / 0.30) × 1.10 (10% tax)
-- plate_cost = sum of ingredient costs + $0.50 garnish overhead
--
-- BREAKFAST & BRUNCH (301)
--  BRK01 Avocado Toast:     avocado(1) + toast(flour) + herbs + evoo = $3.08 → $11.29
INSERT INTO menu_item
  (id, restaurant_id, group_id, pos_id, name, sell_price, target_fc_pct, plate_cost,
   is_active, display_order, created_at, updated_at)
VALUES
  (3011, 3, 301, 'BRK01', 'Avocado Toast',             11.29, 0.30, 3.08, true, 1, '2026-01-01','2026-01-01'),
  (3012, 3, 301, 'BRK02', 'Buttermilk Pancakes',        13.75, 0.30, 3.76, true, 2, '2026-01-01','2026-01-01'),
  (3013, 3, 301, 'BRK03', 'Eggs Benedict',             16.50, 0.30, 4.51, true, 3, '2026-01-01','2026-01-01'),
  (3014, 3, 301, 'BRK04', 'Açaí Power Bowl',           14.85, 0.30, 4.06, true, 4, '2026-01-01','2026-01-01'),
-- SMALL PLATES (302)
--  SPL01 Tuna Tartare:       tuna(0.12lb) + avocado + herbs + evoo = $4.27 → $15.66
  (3021, 3, 302, 'SPL01', 'Tuna Tartare',               15.66, 0.30, 4.27, true, 1, '2026-01-01','2026-01-01'),
  (3022, 3, 302, 'SPL02', 'Burrata with Heirloom Tomato',13.75, 0.30, 3.76, true, 2, '2026-01-01','2026-01-01'),
  (3023, 3, 302, 'SPL03', 'Duck Confit Crostini',       14.85, 0.30, 4.06, true, 3, '2026-01-01','2026-01-01'),
  (3024, 3, 302, 'SPL04', 'Tuna Poke Bowl',             16.50, 0.30, 4.51, true, 4, '2026-01-01','2026-01-01'),
-- MAINS (303)
  (3031, 3, 303, 'MN01',  'NY Strip Steak 12oz',         42.90, 0.30, 6.70, true, 1, '2026-01-01','2026-01-01'),
  (3032, 3, 303, 'MN02',  'Pan-Roasted Salmon',         33.00, 0.30, 5.15, true, 2, '2026-01-01','2026-01-01'),
  (3033, 3, 303, 'MN03',  'Wild Mushroom Risotto',        26.40, 0.30, 4.11, true, 3, '2026-01-01','2026-01-01'),
  (3034, 3, 303, 'MN04',  'Grilled Lamb Rack',            48.40, 0.30, 7.54, true, 4, '2026-01-01','2026-01-01'),
  (3035, 3, 303, 'MN05',  'Heritage Pork Belly',          31.90, 0.30, 4.97, true, 5, '2026-01-01','2026-01-01'),
  (3036, 3, 303, 'MN06',  'Free-Range Duck Breast',       38.50, 0.30, 6.00, true, 6, '2026-01-01','2026-01-01'),
-- SOUPS & SALADS (304)
  (3041, 3, 304, 'SAL01', 'Roasted Beet Salad',          16.50, 0.30, 2.57, true, 1, '2026-01-01','2026-01-01'),
  (3042, 3, 304, 'SAL02', 'French Onion Soup',           13.75, 0.30, 2.14, true, 2, '2026-01-01','2026-01-01'),
  (3043, 3, 304, 'SAL03', 'Classic Caesar Salad',        14.85, 0.30, 2.31, true, 3, '2026-01-01','2026-01-01'),
-- DESSERTS (305)
  (3051, 3, 305, 'DES01', 'NY Cheesecake',               12.10, 0.30, 1.89, true, 1, '2026-01-01','2026-01-01'),
  (3052, 3, 305, 'DES02', 'Crème Brûlée',                11.00, 0.30, 1.71, true, 2, '2026-01-01','2026-01-01'),
  (3053, 3, 305, 'DES03', 'Dark Chocolate Tart',          12.10, 0.30, 1.89, true, 3, '2026-01-01','2026-01-01'),
-- COFFEE & TEA (306) — BEVERAGES use cost-of-goods pricing
  (3061, 3, 306, 'COF01', 'Espresso',                     4.40, 0.20, 0.88, true, 1, '2026-01-01','2026-01-01'),
  (3062, 3, 306, 'COF02', 'Flat White',                   6.60, 0.20, 1.32, true, 2, '2026-01-01','2026-01-01'),
  (3063, 3, 306, 'COF03', 'Matcha Latte',                 6.60, 0.20, 1.32, true, 3, '2026-01-01','2026-01-01'),
  (3064, 3, 306, 'COF04', 'Fresh Orange Juice',          7.70, 0.20, 1.54, true, 4, '2026-01-01','2026-01-01'),
-- WINE BY THE GLASS (307) — 150ml pour, cost ~25% of price
  (3071, 3, 307, 'WIN01', 'Sauvignon Blanc (Glass)',     13.20, 0.25, 2.64, true, 1, '2026-01-01','2026-01-01'),
  (3072, 3, 307, 'WIN02', 'Cabernet Sauvignon (Glass)',  15.40, 0.25, 3.08, true, 2, '2026-01-01','2026-01-01'),
  (3073, 3, 307, 'WIN03', 'Rosé de Provence (Glass)',     13.20, 0.25, 2.64, true, 3, '2026-01-01','2026-01-01'),
  (3074, 3, 307, 'WIN04', 'Chardonnay (Glass)',          14.30, 0.25, 2.86, true, 4, '2026-01-01','2026-01-01'),
-- CRAFT BEER (308) — 16oz pour, cost ~20% of price
  (3081, 3, 308, 'BRW01', 'House IPA (Draft)',             9.90, 0.20, 1.65, true, 1, '2026-01-01','2026-01-01'),
  (3082, 3, 308, 'BRW02', 'Belgian Witbier (Draft)',       9.90, 0.20, 1.65, true, 2, '2026-01-01','2026-01-01'),
  (3083, 3, 308, 'BRW03', 'German Pilsner (Draft)',        8.80, 0.20, 1.47, true, 3, '2026-01-01','2026-01-01')
ON CONFLICT (restaurant_id, pos_id) DO NOTHING;

-- ── RECIPES (one recipe per menu item) ───────────────────────────────────
-- recipe_type: PLATE | BATCH
-- station: GRILL | SAUTE | FRY | SALAD | PASTRY | BAR | COFFEE
INSERT INTO recipe
  (id, restaurant_id, menu_item_id, name, recipe_type, station, yield_quantity, yield_unit, is_active, created_at, updated_at)
VALUES
  -- Breakfast & Brunch
  (3011, 3, 3011, 'Avocado Toast — Recipe',            'PLATE', 'SALAD', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3012, 3, 3012, 'Buttermilk Pancakes — Recipe',      'PLATE', 'FRY', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3013, 3, 3013, 'Eggs Benedict — Recipe',            'PLATE', 'SAUTE', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3014, 3, 3014, 'Açaí Power Bowl — Recipe',         'PLATE', 'SALAD', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  -- Small Plates
  (3021, 3, 3021, 'Tuna Tartare — Recipe',             'PLATE', 'SAUTE', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3022, 3, 3022, 'Burrata — Recipe',                  'PLATE', 'SALAD', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3023, 3, 3023, 'Duck Confit Crostini — Recipe',     'PLATE', 'SAUTE', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3024, 3, 3024, 'Tuna Poke Bowl — Recipe',          'PLATE', 'SALAD', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  -- Mains
  (3031, 3, 3031, 'NY Strip 12oz — Recipe',            'PLATE', 'GRILL', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3032, 3, 3032, 'Pan-Roasted Salmon — Recipe',       'PLATE', 'SAUTE', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3033, 3, 3033, 'Wild Mushroom Risotto — Recipe',    'PLATE', 'SAUTE', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3034, 3, 3034, 'Grilled Lamb Rack — Recipe',       'PLATE', 'GRILL', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3035, 3, 3035, 'Heritage Pork Belly — Recipe',     'PLATE', 'SAUTE', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3036, 3, 3036, 'Duck Breast — Recipe',             'PLATE', 'GRILL', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  -- Soups & Salads
  (3041, 3, 3041, 'Roasted Beet Salad — Recipe',      'PLATE', 'SALAD', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3042, 3, 3042, 'French Onion Soup — Recipe',        'PLATE', 'SAUTE', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3043, 3, 3043, 'Classic Caesar — Recipe',           'PLATE', 'SALAD', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  -- Desserts
  (3051, 3, 3051, 'NY Cheesecake — Recipe',            'PLATE', 'PASTRY', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3052, 3, 3052, 'Crème Brûlée — Recipe',             'PLATE', 'PASTRY', 1.000, 'EACH', true, '2026-01-01','2026-01-01'),
  (3053, 3, 3053, 'Dark Chocolate Tart — Recipe',      'PLATE', 'PASTRY', 1.000, 'EACH', true, '2026-01-01','2026-01-01')
ON CONFLICT (restaurant_id, menu_item_id, name) DO NOTHING;

-- ── RECIPE INGREDIENT LINES ───────────────────────────────────────────────
-- line_number, quantity_ru, recipe_unit
INSERT INTO recipe_ingredient_line
  (id, recipe_id, ingredient_id, line_number, quantity_ru, recipe_unit)
VALUES
  -- BRK01: Avocado Toast (plate_cost = 1.79+0.03+0.10+0.66+0.50 = 3.08)
  (30001, 3011, 301, 1, 1.0, 'EACH'),   -- Avocado
  (30002, 3011, 316, 2, 0.25,'LB'),     -- Flour (toast base)
  (30003, 3011, 306, 3, 0.25,'BUNCH'),  -- Fresh herbs
  (30004, 3011, 318, 4, 0.05,'LITER'),  -- EVOO
  -- BRK02: Buttermilk Pancakes (butter+eggs+flour+maple = 3.76)
  (30005, 3012, 313, 1, 0.10,'LB'),     -- Butter
  (30006, 3012, 305, 2, 2.0, 'EACH'),   -- Eggs
  (30007, 3012, 316, 3, 0.40,'LB'),     -- Flour
  (30008, 3012, 320, 4, 0.10,'GALLON'), -- Maple syrup
  -- BRK03: Eggs Benedict (tuna=eggs+butter+avocado+herbs+evoo = 4.51)
  (30009, 3013, 305, 1, 2.0, 'EACH'),   -- Eggs
  (30010, 3013, 313, 2, 0.15,'LB'),     -- Butter
  (30011, 3013, 301, 3, 0.5, 'EACH'),   -- Avocado
  (30012, 3013, 306, 4, 0.25,'BUNCH'),  -- Fresh herbs
  (30013, 3013, 318, 5, 0.04,'LITER'),  -- EVOO
  -- BRK04: Açaí Bowl (acai = avocado+fruit+grains+honey)
  (30014, 3014, 301, 1, 1.0, 'EACH'),   -- Avocado
  (30015, 3014, 305, 2, 1.0, 'EACH'),   -- Egg (protein)
  (30016, 3014, 316, 3, 0.10,'LB'),     -- Granola/grains
  -- SPL01: Tuna Tartare (tuna+avocado+sesame+soy = 4.27)
  (30017, 3021, 310, 1, 0.12,'LB'),     -- Yellowfin tuna
  (30018, 3021, 301, 2, 0.5, 'EACH'),   -- Avocado
  (30019, 3021, 306, 3, 0.25,'BUNCH'),  -- Scallions/herbs
  -- SPL02: Burrata (burrata+tomato+basil+evoo = 3.76)
  (30020, 3022, 315, 1, 1.0, 'EACH'),   -- Burrata
  (30021, 3022, 302, 2, 0.25,'LB'),     -- Heirloom tomato
  (30022, 3022, 306, 3, 0.25,'BUNCH'),  -- Basil
  -- MN01: NY Strip 12oz (beef 12oz + butter + herbs = 6.70)
  (30023, 3031, 307, 1, 12.0,'LB'),     -- Beef tenderloin
  (30024, 3031, 313, 2, 0.05,'LB'),     -- Butter baste
  (30025, 3031, 306, 3, 0.25,'BUNCH'),  -- Rosemary/thyme
  -- MN02: Pan-Roasted Salmon (salmon + butter + lemon = 5.15)
  (30026, 3032, 309, 1, 8.0, 'LB'),     -- Salmon fillet
  (30027, 3032, 313, 2, 0.05,'LB'),     -- Butter
  -- MN03: Wild Mushroom Risotto (arborio + cream + butter + mushrooms)
  (30028, 3033, 314, 1, 0.50,'GALLON'), -- Heavy cream
  (30029, 3033, 313, 2, 0.10,'LB'),     -- Butter
  (30030, 3033, 306, 3, 1.0, 'BUNCH'), -- Fresh herbs
  -- MN04: Grilled Lamb Rack (lamb + herbs + evoo = 7.54)
  (30031, 3034, 308, 1, 10.0,'LB'),     -- Lamb rack
  (30032, 3034, 306, 2, 0.5, 'BUNCH'), -- Rosemary/herbs
  (30033, 3034, 318, 3, 0.05,'LITER'), -- EVOO marinade
  -- MN05: Heritage Pork Belly (pork + aromatics = 4.97)
  (30034, 3035, 311, 1, 8.0, 'LB'),     -- Pork belly
  -- MN06: Duck Breast (duck + herbs + evoo = 6.00)
  (30035, 3036, 312, 1, 10.0,'LB'),     -- Duck breast
  (30036, 3036, 306, 2, 0.5, 'BUNCH'), -- Fresh herbs
  -- SAL01: Roasted Beet Salad (beets + arugula + goat cheese + vinaigrette)
  (30037, 3041, 304, 1, 0.25,'LB'),     -- Arugula
  (30038, 3041, 303, 2, 0.25,'LB'),     -- Beets/root
  -- SAL02: French Onion Soup (onion + beef stock base + cheese)
  (30039, 3042, 303, 1, 1.0, 'LB'),     -- Yellow onions
  (30040, 3042, 313, 2, 0.05,'LB'),     -- Butter
  -- SAL03: Caesar Salad (romaine + parmesan + dressing)
  (30041, 3043, 304, 1, 0.5, 'LB'),     -- Arugula (or romaine)
  (30042, 3043, 313, 2, 0.05,'LB'),     -- Dressing/butter base
  -- DES01: NY Cheesecake (cream cheese + sugar + eggs + graham = 1.89)
  (30043, 3051, 314, 1, 0.25,'GALLON'), -- Cream base
  (30044, 3051, 317, 2, 0.20,'LB'),     -- Sugar
  -- DES02: Crème Brûlée (cream + vanilla + eggs + sugar = 1.71)
  (30045, 3052, 314, 1, 0.25,'GALLON'), -- Heavy cream
  (30046, 3052, 317, 2, 0.15,'LB'),     -- Sugar
  -- DES03: Dark Chocolate Tart (chocolate + butter + eggs + flour = 1.89)
  (30047, 3053, 313, 1, 0.10,'LB'),     -- Butter
  (30048, 3053, 316, 2, 0.10,'LB')      -- Flour/cocoa base
ON CONFLICT DO NOTHING;

-- ── STAFF (28 employees) ──────────────────────────────────────────────────
-- staff_id uses UUID, pin_hash = BCrypt('0000') for demo — all staff share PIN 0000
-- roles: OWNER | MANAGER | EXECUTIVE_CHEF | SOUS_CHEF | LINE_COOK |
--        PREP_COOK | KITCHEN_MANAGER | FB_MANAGER | HOST | SERVER |
--        BARTENDER | BUSSER | DISHWASHER
INSERT INTO staff
  (staff_id, restaurant_id, display_name, role, pin_hash, pin_length,
   can_take_orders, can_process_payments, can_manage_tables, can_view_reports,
   hourly_rate, is_active, shift_active, created_at, updated_at)
VALUES
  -- Management
  (gen_random_uuid(), 3, 'Amanda Chen',    'OWNER',            '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false,  0.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'David Park',    'GENERAL_MANAGER',  '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, true,  true, 32.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Marcus Webb',    'EXECUTIVE_CHEF',   '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, true, 38.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Sophie Martin', 'SOUS_CHEF',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, true, 28.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'James Rivera',  'KITCHEN_MANAGER',  '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, true, 30.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Emma Wilson',   'FB_MANAGER',       '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, true,  true,  true, 28.00, true, false, '2026-01-01','2026-01-01'),
  -- Kitchen
  (gen_random_uuid(), 3, 'Carlos Diaz',    'LINE_COOK',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 20.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Aisha Johnson',  'LINE_COOK',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 20.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Ryan Thompson',  'LINE_COOK',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 20.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Yuki Tanaka',    'LINE_COOK',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 20.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Alex Brown',     'LINE_COOK',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 20.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Priya Patel',    'LINE_COOK',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 20.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Luis Hernandez', 'PREP_COOK',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 18.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Nina Kovacs',   'PREP_COOK',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 18.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Ben Okafor',    'DISHWASHER',       '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Tom Baker',     'DISHWASHER',       '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 16.00, true, false, '2026-01-01','2026-01-01'),
  -- FOH
  (gen_random_uuid(), 3, 'Grace Kim',     'HOST',             '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, true,  false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Luke Andersen',  'HOST',             '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, true,  false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Maria Santos',  'SENIOR_SERVER',    '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  true,  false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Jack Murphy',   'SENIOR_SERVER',    '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  true,  false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Olivia Chen',   'JUNIOR_SERVER',    '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  false, false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Ethan Brooks',   'JUNIOR_SERVER',    '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  false, false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Isabelle Fox',  'JUNIOR_SERVER',    '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  false, false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Noah Williams', 'JUNIOR_SERVER',    '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  false, false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Sam Taylor',    'JUNIOR_SERVER',    '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  false, false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Mia Scott',     'JUNIOR_SERVER',    '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  false, false, 16.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Chris Lambert', 'BARTENDER',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  false, false, 18.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Zoe Patel',    'BARTENDER',        '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, true,  true,  false, false, 18.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Derek Grant',   'BUSSER',          '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 14.00, true, false, '2026-01-01','2026-01-01'),
  (gen_random_uuid(), 3, 'Kate Mills',    'BUSSER',          '$2a$10$UvCbKrvh7ey1PlgxPwoH..7m.waBgE0KDwDFxfe6Wf16hNAjlpxUa', 4, false, false, false, false, 14.00, true, false, '2026-01-01','2026-01-01');

-- ── WEEKLY BUDGET ──────────────────────────────────────────────────────────
-- Sales mix targets for Modern Casual NY restaurant
-- Avg check ~$55/person × 2.4 guests × 96 covers/day = ~$12,672/day → $88,704/week
-- But this is PREMIUM casual, realistic: $40K/week revenue
-- Tax: 10% (NY sales tax)
INSERT INTO weekly_budget
  (id, restaurant_id, week_start_date,
   total_sales_forecast,
   food_sales_pct, soft_bev_sales_pct, liquor_sales_pct,
   bottle_beer_sales_pct, draft_beer_sales_pct, wine_sales_pct, comps_pct,
   food_cos_pct_target, bev_cos_pct_target,
   mgmt_labor_pct_target, hourly_labor_pct_target, benefits_rate,
   fixed_costs,
   created_at, updated_at)
VALUES
  (3, 3, '2026-01-06',
   45000.00,   -- total weekly sales forecast
   0.62,       -- food: 62% of sales (mains + small plates + breakfast + desserts)
   0.08,       -- soft bev: 8% (coffee + juice)
   0.00,       -- liquor: 0% (no full bar, wine only)
   0.05,       -- bottled beer: 5%
   0.05,       -- draft beer: 5%
   0.15,       -- wine: 15%
   0.05,       -- comps: 5%
   0.30,       -- food cost target: 30%
   0.20,       -- bev cost target: 20%
   0.08,       -- mgmt labor: 8% of sales
   0.22,       -- hourly labor: 22% of sales
   0.20,       -- benefits: 20% of labor
   2000.00,    -- fixed costs (rent allocation)
   '2026-01-01','2026-01-01')
ON CONFLICT (restaurant_id, week_start_date) DO NOTHING;


-- ── SAMPLE ORDERS: Moved to a future migration (V10+)
-- The complex SELECT-based inserts need refactoring for Flyway compatibility.
-- See the original V6 for the sample order data.
/*
-- ── SAMPLE ORDERS (20 historical PAID orders for demo) ───────────────────
-- 7 days ago (the restaurant has been running 1 week)
INSERT INTO table_session (id, table_id, restaurant_id, guest_count, opened_at, closed_at)
SELECT
  s.id, t.id, 3, 2 + (s.n % 4),
  (CURRENT_TIMESTAMP - INTERVAL '7 days' + (s.n * INTERVAL '90 minutes')),
  (CURRENT_TIMESTAMP - INTERVAL '7 days' + ((s.n+1) * INTERVAL '90 minutes'))
FROM dining_table t
CROSS JOIN generate_series(1, 20) AS s(n)
WHERE t.restaurant_id = 3 AND t.table_number = 'T'||lpad(((s.n-1) % 8 + 1)::text, 2, '0')
ON CONFLICT DO NOTHING;

-- Orders per session (random menu items from the menu)
INSERT INTO restaurant_order
  (id, restaurant_id, session_id, order_number, total_amount, tax_amount,
   tip_amount, discount_amount, status, created_at)
SELECT
  3000 + s.n,
  3,
  (SELECT id FROM table_session WHERE restaurant_id = 3 ORDER BY id LIMIT 1 OFFSET (s.n - 1)),
  'ORD-MKT-'||to_char(CURRENT_DATE - INTERVAL '7 days', 'YYMMDD')||'-'||lpad(s.n::text, 3, '0'),
  -- total: mix of items (2-4 items per order)
  CASE WHEN s.n % 5 = 0 THEN 42.90    -- steak order
       WHEN s.n % 5 = 1 THEN 33.00   -- salmon order
       WHEN s.n % 5 = 2 THEN 55.80   -- shared plates
       WHEN s.n % 5 = 3 THEN 27.50   -- brunch for two
       ELSE 78.90                      -- large group
  END,
  CASE WHEN s.n % 5 = 0 THEN 4.29
       WHEN s.n % 5 = 1 THEN 3.30
       WHEN s.n % 5 = 2 THEN 5.58
       WHEN s.n % 5 = 3 THEN 2.75
       ELSE 7.89
  END,
  CASE WHEN s.n % 5 = 0 THEN 8.58
       WHEN s.n % 5 = 1 THEN 6.60
       WHEN s.n % 5 = 2 THEN 11.16
       WHEN s.n % 5 = 3 THEN 5.50
       ELSE 15.78
  END,
  0.00,
  'PAID',
  (CURRENT_TIMESTAMP - INTERVAL '7 days' + (s.n * INTERVAL '90 minutes'))
FROM generate_series(1, 20) AS s(n)
ON CONFLICT DO NOTHING;

-- Order lines (at least 1-2 items per order)
INSERT INTO order_line
  (id, order_id, menu_item_id, quantity, unit_price, subtotal)
VALUES
  -- Order 1: NY Strip order
  (30001, 3001, 3031, 1, 42.90, 42.90),
  (30002, 3001, 3043, 1, 14.85, 14.85),
  -- Order 2: Salmon order
  (30003, 3002, 3032, 1, 33.00, 33.00),
  (30004, 3002, 3041, 1, 16.50, 16.50),
  -- Order 3: Shared plates
  (30005, 3003, 3021, 2, 15.66, 31.32),
  (30006, 3003, 3024, 1, 16.50, 16.50),
  (30007, 3003, 3081, 2, 9.90,  19.80),
  -- Order 4: Brunch
  (30008, 3004, 3012, 2, 13.75, 27.50),
  -- Order 5: Large group
  (30009, 3005, 3031, 2, 42.90, 85.80),
  (30010, 3005, 3034, 1, 48.40, 48.40),
  (30011, 3005, 3081, 3, 9.90,  29.70),
  -- Orders 6-20: repeat pattern
  (30012, 3006, 3032, 1, 33.00, 33.00),
  (30013, 3007, 3022, 2, 13.75, 27.50),
  (30014, 3008, 3013, 2, 16.50, 33.00),
  (30015, 3009, 3036, 1, 38.50, 38.50),
  (30016, 3010, 3071, 2, 13.20, 26.40),
  (30017, 3011, 3031, 1, 42.90, 42.90),
  (30018, 3012, 3023, 1, 14.85, 14.85),
  (30019, 3013, 3011, 2, 11.29, 22.58),
  (30020, 3014, 3033, 1, 26.40, 26.40)
ON CONFLICT DO NOTHING;

-- ── INVENTORY LEDGER — initial opening stock ────────────────────────────────
-- event_type values (from StockMovementType enum):
--   OPENING_STOCK   ← opening count for new restaurant
--   RECEIVING       ← shipment intake from GRN
--   DEPLETION       ← POS-driven recipe consumption
--   ADJUSTMENT      ← manual count corrections
--   PRODUCTION_IN   ← prepped stock from batching
--
-- All 20 ingredients receive opening stock equal to par_level.
-- unit_cost = purchase_unit_price per PU (same as ingredient.purchase_unit_price).
-- par_level is set on the ingredient itself (restocked when on_hand ≤ par * 0.5).
--
-- The ledger is an AUDIT log — each movement is one row.
-- total_value = quantity_change × unit_cost (PostgreSQL will calculate if column is COMPUTED,
-- otherwise we set it explicitly here).
INSERT INTO inventory_ingredient_ledger
  (id, restaurant_id, ingredient_id, event_type, quantity_change,
   unit_cost, total_value, reason, recorded_at, created_at)
SELECT
  3000 + i.n,
  3, i.id,
  'OPENING_STOCK',
  -- opening stock = par_level (restaurant starts fully stocked)
  i.par_level,
  i.purchase_unit_price,
  -- total_value = par_level × unit_cost (round to 4 dp)
  round(i.par_level * i.purchase_unit_price, 4),
  'Initial opening stock — The Market Table Restaurant',
  '2026-01-01',
  '2026-01-01'
FROM generate_series(301, 320) AS i(n)
JOIN ingredient ing ON ing.id = i.n
ON CONFLICT DO NOTHING;


-- ═══════════════════════════════════════════════════════════════════════════
-- SUMMARY
-- Tables inserted:
--   restaurant          : 1 row
--   dining_table        : 24 rows
--   supplier            : 5 rows
--   ingredient          : 20 rows
--   menu_cost_group     : 8 rows  (revenueCategory: FOOD ×5, SOFT_BEV ×1, WINE ×1, BEER ×1)
--   menu_item           : 27 rows
--   recipe              : 20 rows
--   recipe_ingredient_line: 48 rows
--   staff               : 28 rows
--   weekly_budget       : 1 row
--   table_session        : 20 rows
--   restaurant_order     : 20 rows
--   order_line          : 20 rows
--   inventory_ledger    : 20 rows
--
-- Revenue category breakdown (for Prime Cost reporting):
--   FOOD     : 18 items (Breakfast ×4, Small Plates ×4, Mains ×6, Soups ×3, Desserts ×3)
--   SOFT_BEV : 4 items (Coffee ×4)
--   WINE     : 4 items (Wine ×4)
--   BEER     : 3 items (Craft Beer ×3)
--   Total    : 29 menu items
-- ═══════════════════════════════════════════════════════════════════════════

*/
