// Mocks generated by Mockito 5.4.6 from annotations
// in shopro_pos_flutter/test/features/order/presentation/providers/order_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i10;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shopro_pos_flutter/core/network/api_client.dart' as _i7;
import 'package:shopro_pos_flutter/features/order/domain/models/order_models.dart'
    as _i2;
import 'package:shopro_pos_flutter/features/order/domain/repositories/order_repository.dart'
    as _i5;
import 'package:stomp_dart_client/src/stomp.dart' as _i8;
import 'package:stomp_dart_client/src/stomp_config.dart' as _i4;
import 'package:stomp_dart_client/src/stomp_handler.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrderTicket_0 extends _i1.SmartFake implements _i2.OrderTicket {
  _FakeOrderTicket_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStompConfig_3 extends _i1.SmartFake implements _i4.StompConfig {
  _FakeStompConfig_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i5.OrderRepository {
  @override
  _i6.Future<_i2.OrderTicket> getOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrder, [orderId]),
            returnValue: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(this, Invocation.method(#getOrder, [orderId])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(this, Invocation.method(#getOrder, [orderId])),
            ),
          )
          as _i6.Future<_i2.OrderTicket>);

  @override
  _i6.Future<List<_i2.OrderTicket>> getActiveOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveOrders, []),
            returnValue: _i6.Future<List<_i2.OrderTicket>>.value(
              <_i2.OrderTicket>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i2.OrderTicket>>.value(
              <_i2.OrderTicket>[],
            ),
          )
          as _i6.Future<List<_i2.OrderTicket>>);

  @override
  _i6.Future<_i2.OrderTicket> fireCourse(String? orderId, int? courseNumber) =>
      (super.noSuchMethod(
            Invocation.method(#fireCourse, [orderId, courseNumber]),
            returnValue: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#fireCourse, [orderId, courseNumber]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#fireCourse, [orderId, courseNumber]),
              ),
            ),
          )
          as _i6.Future<_i2.OrderTicket>);

  @override
  _i6.Future<_i2.OrderTicket> sendToKitchen(
    String? orderId, {
    String? idempotencyKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendToKitchen,
              [orderId],
              {#idempotencyKey: idempotencyKey},
            ),
            returnValue: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(
                  #sendToKitchen,
                  [orderId],
                  {#idempotencyKey: idempotencyKey},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(
                  #sendToKitchen,
                  [orderId],
                  {#idempotencyKey: idempotencyKey},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.OrderTicket>);

  @override
  _i6.Future<_i2.OrderTicket> createOrder({
    required String? tableId,
    required int? guestCount,
    required _i2.OrderType? orderType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #tableId: tableId,
              #guestCount: guestCount,
              #orderType: orderType,
            }),
            returnValue: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#createOrder, [], {
                  #tableId: tableId,
                  #guestCount: guestCount,
                  #orderType: orderType,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#createOrder, [], {
                  #tableId: tableId,
                  #guestCount: guestCount,
                  #orderType: orderType,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.OrderTicket>);

  @override
  _i6.Future<_i2.OrderTicket> addOrderItem(
    String? orderId,
    Map<String, dynamic>? itemData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addOrderItem, [orderId, itemData]),
            returnValue: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#addOrderItem, [orderId, itemData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#addOrderItem, [orderId, itemData]),
              ),
            ),
          )
          as _i6.Future<_i2.OrderTicket>);

  @override
  _i6.Future<_i2.OrderTicket> updateOrderItem(
    String? orderId,
    String? itemId,
    Map<String, dynamic>? itemData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderItem, [orderId, itemId, itemData]),
            returnValue: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#updateOrderItem, [
                  orderId,
                  itemId,
                  itemData,
                ]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#updateOrderItem, [
                  orderId,
                  itemId,
                  itemData,
                ]),
              ),
            ),
          )
          as _i6.Future<_i2.OrderTicket>);

  @override
  _i6.Future<List<_i2.OrderTicket>> getOrderHistory({
    String? orderId,
    String? tableName,
    DateTime? startDate,
    DateTime? endDate,
    String? serverName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderHistory, [], {
              #orderId: orderId,
              #tableName: tableName,
              #startDate: startDate,
              #endDate: endDate,
              #serverName: serverName,
            }),
            returnValue: _i6.Future<List<_i2.OrderTicket>>.value(
              <_i2.OrderTicket>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i2.OrderTicket>>.value(
              <_i2.OrderTicket>[],
            ),
          )
          as _i6.Future<List<_i2.OrderTicket>>);

  @override
  _i6.Future<void> initiateMiPay(String? orderId, String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#initiateMiPay, [orderId, phoneNumber]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> completePayment(
    String? orderId,
    _i2.PaymentMethod? method,
    double? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completePayment, [orderId, method, amount]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.OrderTicket> markAsServed(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsServed, [orderId]),
            returnValue: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#markAsServed, [orderId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(#markAsServed, [orderId]),
              ),
            ),
          )
          as _i6.Future<_i2.OrderTicket>);

  @override
  _i6.Future<_i2.OrderTicket> cancelOrder(
    String? orderId, {
    String? managerPin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cancelOrder,
              [orderId],
              {#managerPin: managerPin},
            ),
            returnValue: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(
                  #cancelOrder,
                  [orderId],
                  {#managerPin: managerPin},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(
                  #cancelOrder,
                  [orderId],
                  {#managerPin: managerPin},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.OrderTicket>);

  @override
  _i6.Future<_i2.OrderTicket> voidOrderItem(
    String? orderId,
    String? itemId,
    String? reason, {
    String? managerPin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #voidOrderItem,
              [orderId, itemId, reason],
              {#managerPin: managerPin},
            ),
            returnValue: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(
                  #voidOrderItem,
                  [orderId, itemId, reason],
                  {#managerPin: managerPin},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OrderTicket>.value(
              _FakeOrderTicket_0(
                this,
                Invocation.method(
                  #voidOrderItem,
                  [orderId, itemId, reason],
                  {#managerPin: managerPin},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.OrderTicket>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i7.ApiClient {
  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_1(this, Invocation.getter(#dio)),
            returnValueForMissingStub: _FakeDio_1(
              this,
              Invocation.getter(#dio),
            ),
          )
          as _i3.Dio);

  @override
  set dio(_i3.Dio? _dio) => super.noSuchMethod(
    Invocation.setter(#dio, _dio),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i3.Response<dynamic>> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {#data: data, #queryParameters: queryParameters},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {#data: data, #queryParameters: queryParameters},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {#data: data, #queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i6.Future<_i3.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i6.Future<_i3.Response<dynamic>> patch(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {#data: data, #queryParameters: queryParameters},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {#data: data, #queryParameters: queryParameters},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {#data: data, #queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i6.Future<_i3.Response<dynamic>> delete(
    String? path, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);
}

/// A class which mocks [StompClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStompClient extends _i1.Mock implements _i8.StompClient {
  @override
  _i4.StompConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeStompConfig_3(this, Invocation.getter(#config)),
            returnValueForMissingStub: _FakeStompConfig_3(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i4.StompConfig);

  @override
  bool get connected =>
      (super.noSuchMethod(
            Invocation.getter(#connected),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isActive =>
      (super.noSuchMethod(
            Invocation.getter(#isActive),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void activate() => super.noSuchMethod(
    Invocation.method(#activate, []),
    returnValueForMissingStub: null,
  );

  @override
  void deactivate() => super.noSuchMethod(
    Invocation.method(#deactivate, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.StompUnsubscribe subscribe({
    required String? destination,
    required _i4.StompFrameCallback? callback,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #destination: destination,
              #callback: callback,
              #headers: headers,
            }),
            returnValue: ({Map<String, String>? unsubscribeHeaders}) {},
            returnValueForMissingStub:
                ({Map<String, String>? unsubscribeHeaders}) {},
          )
          as _i9.StompUnsubscribe);

  @override
  void send({
    required String? destination,
    Map<String, String>? headers,
    String? body,
    _i10.Uint8List? binaryBody,
  }) => super.noSuchMethod(
    Invocation.method(#send, [], {
      #destination: destination,
      #headers: headers,
      #body: body,
      #binaryBody: binaryBody,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void ack({required String? id, Map<String, String>? headers}) =>
      super.noSuchMethod(
        Invocation.method(#ack, [], {#id: id, #headers: headers}),
        returnValueForMissingStub: null,
      );

  @override
  void nack({required String? id, Map<String, String>? headers}) =>
      super.noSuchMethod(
        Invocation.method(#nack, [], {#id: id, #headers: headers}),
        returnValueForMissingStub: null,
      );
}
