// Mocks generated by Mockito 5.4.6 from annotations
// in shopro_pos_flutter/test/features/kds/presentation/providers/kds_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shopro_pos_flutter/features/kds/domain/models/kds_models.dart'
    as _i2;
import 'package:shopro_pos_flutter/features/kds/domain/repositories/kds_repository.dart'
    as _i4;
import 'package:stomp_dart_client/src/stomp.dart' as _i6;
import 'package:stomp_dart_client/src/stomp_config.dart' as _i3;
import 'package:stomp_dart_client/src/stomp_handler.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKDSTicket_0 extends _i1.SmartFake implements _i2.KDSTicket {
  _FakeKDSTicket_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKDSTicketItem_1 extends _i1.SmartFake implements _i2.KDSTicketItem {
  _FakeKDSTicketItem_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKDSStation_2 extends _i1.SmartFake implements _i2.KDSStation {
  _FakeKDSStation_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStompConfig_3 extends _i1.SmartFake implements _i3.StompConfig {
  _FakeStompConfig_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KDSRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKDSRepository extends _i1.Mock implements _i4.KDSRepository {
  MockKDSRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.KDSTicket>> getActiveTickets(String? stationId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTickets, [stationId]),
            returnValue: _i5.Future<List<_i2.KDSTicket>>.value(
              <_i2.KDSTicket>[],
            ),
          )
          as _i5.Future<List<_i2.KDSTicket>>);

  @override
  _i5.Future<_i2.KDSTicket> bumpTicket(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#bumpTicket, [ticketId]),
            returnValue: _i5.Future<_i2.KDSTicket>.value(
              _FakeKDSTicket_0(
                this,
                Invocation.method(#bumpTicket, [ticketId]),
              ),
            ),
          )
          as _i5.Future<_i2.KDSTicket>);

  @override
  _i5.Future<_i2.KDSTicketItem> bumpItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#bumpItem, [itemId]),
            returnValue: _i5.Future<_i2.KDSTicketItem>.value(
              _FakeKDSTicketItem_1(
                this,
                Invocation.method(#bumpItem, [itemId]),
              ),
            ),
          )
          as _i5.Future<_i2.KDSTicketItem>);

  @override
  _i5.Future<List<_i2.KDSStation>> getAllStations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllStations, []),
            returnValue: _i5.Future<List<_i2.KDSStation>>.value(
              <_i2.KDSStation>[],
            ),
          )
          as _i5.Future<List<_i2.KDSStation>>);

  @override
  _i5.Future<_i2.KDSStation> getStationById(String? stationId) =>
      (super.noSuchMethod(
            Invocation.method(#getStationById, [stationId]),
            returnValue: _i5.Future<_i2.KDSStation>.value(
              _FakeKDSStation_2(
                this,
                Invocation.method(#getStationById, [stationId]),
              ),
            ),
          )
          as _i5.Future<_i2.KDSStation>);

  @override
  _i5.Future<_i2.KDSTicketItem> updateItemPriority(
    String? itemId,
    int? priority,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemPriority, [itemId, priority]),
            returnValue: _i5.Future<_i2.KDSTicketItem>.value(
              _FakeKDSTicketItem_1(
                this,
                Invocation.method(#updateItemPriority, [itemId, priority]),
              ),
            ),
          )
          as _i5.Future<_i2.KDSTicketItem>);

  @override
  _i5.Future<_i2.KDSTicketItem> toggleItemStatus(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleItemStatus, [itemId]),
            returnValue: _i5.Future<_i2.KDSTicketItem>.value(
              _FakeKDSTicketItem_1(
                this,
                Invocation.method(#toggleItemStatus, [itemId]),
              ),
            ),
          )
          as _i5.Future<_i2.KDSTicketItem>);

  @override
  _i5.Future<_i2.KDSTicketItem> markItemReady(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#markItemReady, [itemId]),
            returnValue: _i5.Future<_i2.KDSTicketItem>.value(
              _FakeKDSTicketItem_1(
                this,
                Invocation.method(#markItemReady, [itemId]),
              ),
            ),
          )
          as _i5.Future<_i2.KDSTicketItem>);

  @override
  _i5.Future<_i2.KDSTicketItem> serveItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#serveItem, [itemId]),
            returnValue: _i5.Future<_i2.KDSTicketItem>.value(
              _FakeKDSTicketItem_1(
                this,
                Invocation.method(#serveItem, [itemId]),
              ),
            ),
          )
          as _i5.Future<_i2.KDSTicketItem>);

  @override
  _i5.Future<void> serveReadyItems(List<String>? ticketIds) =>
      (super.noSuchMethod(
            Invocation.method(#serveReadyItems, [ticketIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [StompClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStompClient extends _i1.Mock implements _i6.StompClient {
  MockStompClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.StompConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeStompConfig_3(this, Invocation.getter(#config)),
          )
          as _i3.StompConfig);

  @override
  bool get connected =>
      (super.noSuchMethod(Invocation.getter(#connected), returnValue: false)
          as bool);

  @override
  bool get isActive =>
      (super.noSuchMethod(Invocation.getter(#isActive), returnValue: false)
          as bool);

  @override
  void activate() => super.noSuchMethod(
    Invocation.method(#activate, []),
    returnValueForMissingStub: null,
  );

  @override
  void deactivate() => super.noSuchMethod(
    Invocation.method(#deactivate, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.StompUnsubscribe subscribe({
    required String? destination,
    required _i3.StompFrameCallback? callback,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #destination: destination,
              #callback: callback,
              #headers: headers,
            }),
            returnValue: ({Map<String, String>? unsubscribeHeaders}) {},
          )
          as _i7.StompUnsubscribe);

  @override
  void send({
    required String? destination,
    Map<String, String>? headers,
    String? body,
    _i8.Uint8List? binaryBody,
  }) => super.noSuchMethod(
    Invocation.method(#send, [], {
      #destination: destination,
      #headers: headers,
      #body: body,
      #binaryBody: binaryBody,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void ack({required String? id, Map<String, String>? headers}) =>
      super.noSuchMethod(
        Invocation.method(#ack, [], {#id: id, #headers: headers}),
        returnValueForMissingStub: null,
      );

  @override
  void nack({required String? id, Map<String, String>? headers}) =>
      super.noSuchMethod(
        Invocation.method(#nack, [], {#id: id, #headers: headers}),
        returnValueForMissingStub: null,
      );
}
