package mls.sho.dms.application.simulator.core;

import lombok.Builder;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import java.io.*;
import java.nio.file.Path;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;

/**
 * Utility class to decode the binary .simlog files generated by the SimulationLogger.
 */
@Slf4j
public class SimulationLogReader {

    @Data
    @Builder
    public static class LogEntry {
        private LocalDateTime realTime;
        private LocalDateTime simTime;
        private byte agentType;
        private long agentId;
        private byte eventType;
        private String message;

        public String getAgentTypeName() {
            return switch (agentType) {
                case SimulationLogger.AGENT_CUSTOMER -> "CUSTOMER";
                case SimulationLogger.AGENT_STAFF -> "STAFF";
                case SimulationLogger.AGENT_KITCHEN -> "KITCHEN";
                default -> "SYSTEM";
            };
        }

        public String getEventTypeName() {
            return switch (eventType) {
                case SimulationLogger.EVENT_START -> "START";
                case SimulationLogger.EVENT_TRANSITION -> "TRANSITION";
                case SimulationLogger.EVENT_ACTION -> "ACTION";
                case SimulationLogger.EVENT_FINISH -> "FINISH";
                default -> "UNKNOWN";
            };
        }
    }

    /**
     * Reads a binary simulation log and returns a list of human-readable entries.
     */
    public List<LogEntry> readLog(Path path) throws IOException {
        List<LogEntry> entries = new ArrayList<>();
        ZoneId zone = ZoneId.systemDefault();

        try (DataInputStream in = new DataInputStream(new BufferedInputStream(new FileInputStream(path.toFile())))) {
            while (in.available() > 0) {
                try {
                    LogEntry entry = LogEntry.builder()
                            .realTime(LocalDateTime.ofInstant(Instant.ofEpochMilli(in.readLong()), zone))
                            .simTime(LocalDateTime.ofInstant(Instant.ofEpochMilli(in.readLong()), zone))
                            .agentType(in.readByte())
                            .agentId(in.readLong())
                            .eventType(in.readByte())
                            .message(in.readUTF())
                            .build();
                    entries.add(entry);
                } catch (EOFException e) {
                    break; 
                }
            }
        } catch (FileNotFoundException e) {
            log.error("Log file not found: {}", path);
            throw e;
        }
        
        log.info("Read {} entries from {}", entries.size(), path.getFileName());
        return entries;
    }
}
